# -*- coding: utf-8 -*-
"""Deci level 2 week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_2t2cRj9NpAz1ZJgz80eaOduhNqWmao
"""

name = input("What's Your Name : \n")
age = int(input("How old are you ? \n"))
favorite_subject = input("What's Your favorite subject : \n")
favorite_hobby = input("What's Your favorite hobby : \n")
dream_job = input("What's Your dream job : \n")

print("==================================== YOUR PROFILE CARD ====================================")
print(f"Name : {name}, Age : {age}, favorite subject : {favorite_subject}, favorite hobby : {favorite_hobby}, dream job : {dream_job}")
print("Did you know? In 10 years,", name , "will be " , age + 10 , "years old .")